### ISSUE TITLE
"20 миллиардов долларов" is recognized as 1 billion

### ISSUE THREAD

**Issue by vova-lantsov-dev** [VirtualSoftKey/exchange-rates-tg-bot#11]
Input text: `20 миллиардов долларов`
Expected result: `20.000.000.000`
Actual result: `1.000.000.000`

**Comment by volkovskey** [comment]
![image](https://user-images.githubusercontent.com/60794004/236621430-577bb236-7648-4662-935b-8136813ac6eb.png)
Fixed
